apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.16.20.20-172.16.20.21
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: layer2-first-pool
  namespace: metallb-system
spec:
  ipAddressPools:
    - first-pool
